FROM openjdk:11-jdk-slim

WORKDIR /app

COPY gradlew ./
COPY gradle/ ./gradle/
COPY build.gradle ./
COPY settings.gradle ./
COPY src ./src

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*
RUN ./gradlew jar
RUN cp build/libs/*.jar app.jar

COPY entrypoint.sh ./
COPY dump_jstack.sh ./
RUN touch dump_jstack.sh # Force Docker to see a change
RUN chmod +x entrypoint.sh dump_jstack.sh

ENTRYPOINT ["/app/entrypoint.sh"]
CMD []